apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-replicaset-tollerence
  labels:
      app: myapp
      type: front-end
spec:
  template:
      metadata:
         name: myapp-pod
         labels: 
             app: myapp
             type: front-end
      spec:
        tolerations:
        - key: "taintdemo"
          operator: "Equal"
          value: "yo"
          effect: "NoSchedule"
          #tolerationSeconds: 5
        containers:
        - name: nginx-containers
          image: nginx
  replicas: 1
  selector:
     matchLabels:
        type: front-end
