apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
      app: myapp
      type: backend-end
spec:
  template:
      metadata:
         name: myapp-pod
         labels: 
             app: myapp
             type: backend-end
      spec:
        containers:
        - name: nginx-containers
          image: yogeshraheja/yogeshk8stest 
  replicas: 2
  selector:
     matchLabels:
        type: backend-end
