apiVersion: v1
kind: Service
metadata:
 name: myapp-deployment-custom-service
 labels:
  app: myapp
  type: backend-end 
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    #containerPort: 80
    nodePort: 32000
    protocol: TCP

  selector:
    type: backend-end
